steps:

  # ! build
  # installation des dépendances 
  # un "builder" est un container avec certaines dépendances pré installées
  - name: python # nom du "builder"
    # nom du programme en entrée pour cette étape de pipeline
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
    id: "installation des dépendances"

    # ! test
  - name: python
    # nom du programme en entrée pour cette étape de pipeline
    entrypoint: python
    args: ["-m", "pytest"]
    id: "test de l'application"

    # ! deploy
  # build l'image Docker de l'application
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/serfa-gcp/$REPO_NAME/flasksample:$SHORT_SHA",
        "-f",
        "prod.Dockerfile",
        ".",
      ]
    id: Build
  # push de l'image sur Google Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "europe-west1-docker.pkg.dev/serfa-gcp/$REPO_NAME/flasksample:$SHORT_SHA"
    id: Push
    
    # TODO deployer cette image en tant que service Cloud Run
  # déploiement sur Google Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - run
      - services
      - update
      - serfa-gcp-tp
      - "--platform=managed"
      - "--port=5000"
      - "--image=europe-west1-docker.pkg.dev/serfa-gcp/$REPO_NAME/flasksample:$SHORT_SHA"
      - "--region=europe-west1"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud