steps:

  # ! build
  # installation des dépendances 
  - name: python
    # nom du programme en entrée pour cette étape de pipeline
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
    id: "Install"

    # ! test
  - name: python
    # nom du programme en entrée pour cette étape de pipeline
    entrypoint: python
    args: ["-m", "pytest"]
    id: "Test"

    # ! deploy
    # TODO
